In [1]:
import torch

1. On the tensor, set ``.requires_grad`` as ``True``, to track all operations on it. 
2. After computation, call ``.backward()`` and have all the gradients computed automatically. 
3. The gradient for this tensor will be accumulated into ``.grad`` attribute.

In [19]:
# Create a tensor and set requires_grad=True to track computation with it

def rosenbrock(x):
    return 100*(x[1] - x[0]**2)**2 + (1 - x[0])**2

x = torch.ones(2, requires_grad=True)

x[0] = 1
x[1] = 3

print(x)

z = rosenbrock(x)
out = z.mean()
out.backward(torch.tensor(2))
# y = x + 2
# z = y * y * 3
# out = z.mean()
# print(z, out)
# out.backward()
# print(x.grad)


# # Another example
# x = torch.randn(3, requires_grad=True)

# y = x * 2
# while y.data.norm() < 1000:
#     y = y * 2

# print(y) # y will have a  grad_fn=<MulBackward>
# gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
# y.backward(gradients)
# print(x.grad)

# #Stop autograd from tracking history on Tensors
# print(x.requires_grad)
# print((x ** 2).requires_grad)
# with torch.no_grad():
#     print((x ** 2).requires_grad)

tensor([1., 3.], grad_fn=<CopySlices>)


RuntimeError: invalid gradient at index 0 - expected type torch.FloatTensor but got torch.LongTensor

In [22]:
from torch import FloatTensor
from torch.autograd import Variable


# Define the leaf nodes
a = Variable(FloatTensor([4]))

weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (2, 5, 9, 7)]

# unpack the weights for nicer assignment
w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
L = (10 - d)

L.backward()

for index, weight in enumerate(weights, start=1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to L: {gradient}")

Gradient of w1 w.r.t to L: -36.0
Gradient of w2 w.r.t to L: -28.0
Gradient of w3 w.r.t to L: -8.0
Gradient of w4 w.r.t to L: -20.0


In [29]:
from torch import FloatTensor
from torch.autograd import Variable

x = [Variable(FloatTensor([1]), requires_grad=True), 
     Variable(FloatTensor([3]), requires_grad=True)]
y = rosenbrock(x)
y.backward()
print(y, x[0].grad, x[1].grad)
print()
print()
# for index, weight in enumerate(weights, start=1):
#     gradient, *_ = weight.grad.data
#     print(f"Gradient of w{index} w.r.t to L: {gradient}")

tensor([400.], grad_fn=<ThAddBackward>)
tensor([-800.])
tensor([400.])
